server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**

        - id: user-login
          uri: lb://user-service
          predicates:
            - Path=/login

        - id: survey-service
          uri: lb://survey-service
          predicates:
            - Path=/api/surveys/**

        - id: response-service
          uri: lb://response-service
          predicates:
            - Path=/api/responses/**

        - id: report-service
          uri: lb://report-service
          predicates:
            - Path=/api/reports/**

        - id: advertise-service
          uri: lb://advertise-service
          predicates:
            - Path=/api/advertisements/**